# Site settings
title: Zoë Bryant
email: zoeabryant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 One of my Makers Academy coaches told me that the most difficult questions to answer are the ones that start with: 'Can I make this?'. I like to ask a lot of those questions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://zoeabryant.github.io/ # the base hostname & protocol for your site
twitter_username: zoeabryant
github_username:  zoeabryant

# Build settings
markdown: rdiscount
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
